### ISSUE TITLE
Scaled GIFs seem to bypass parts of processing pipeline

### ISSUE THREAD

**Issue by evenwestvang** [rexxars/mead#17]
The following URL should presumably present a 300px wide image with a 50px blur applied, but is totally sharp. Supposedly.

`https://cdn.sanity.io/images/q2tdbkqz/production/cFBn8yiY5Btjznd61mga8Gic-3000x1817.gif?w=300&blur=50`

Super stoked that there's gaussian blur BTW! 💯

**Comment by rexxars** [comment]
Gifs are set as a passthrough format because vips does not support outputting to gif. You could force it to jpg if you want: https://cdn.sanity.io/images/q2tdbkqz/production/cFBn8yiY5Btjznd61mga8Gic-3000x1817.gif?w=300&blur=50&fm=jpg
